server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/todo
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - com/sample/mapper/*.xml